// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw2dp36em023y2byaQgi5fkUctvl1cCZM',
    appId: '1:299616748724:web:e816afb611141fe9fd83e1',
    messagingSenderId: '299616748724',
    projectId: 'datamine-da51e',
    authDomain: 'datamine-da51e.firebaseapp.com',
    storageBucket: 'datamine-da51e.appspot.com',
    measurementId: 'G-P1W3FTTW0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgObX2nzB-5vzhjvq73N7Oo2M3Us6g7mc',
    appId: '1:299616748724:android:bf788a3a6431624afd83e1',
    messagingSenderId: '299616748724',
    projectId: 'datamine-da51e',
    storageBucket: 'datamine-da51e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQUP8AKTrJnkfo96d7piusHQTzRZOAIKU',
    appId: '1:299616748724:ios:f71c54e058cbade4fd83e1',
    messagingSenderId: '299616748724',
    projectId: 'datamine-da51e',
    storageBucket: 'datamine-da51e.appspot.com',
    iosBundleId: 'com.example.datamine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQUP8AKTrJnkfo96d7piusHQTzRZOAIKU',
    appId: '1:299616748724:ios:f71c54e058cbade4fd83e1',
    messagingSenderId: '299616748724',
    projectId: 'datamine-da51e',
    storageBucket: 'datamine-da51e.appspot.com',
    iosBundleId: 'com.example.datamine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw2dp36em023y2byaQgi5fkUctvl1cCZM',
    appId: '1:299616748724:web:6ed561965b3deeaffd83e1',
    messagingSenderId: '299616748724',
    projectId: 'datamine-da51e',
    authDomain: 'datamine-da51e.firebaseapp.com',
    storageBucket: 'datamine-da51e.appspot.com',
    measurementId: 'G-HNHGQ4SK3Q',
  );
}
